# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Deprecate Repo Notice

on:
  pull_request:
    types:
      # run this only when opening a PR, not every time
      - opened
    branches:
      - "main"

permissions: {}

jobs:
  changes:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false

      - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05 # v1.1.1
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: deprecate-repo

      - name: Deprecated Repo
        shell: bash
        run: |
          echo "*******************************************************************"
          echo "This repository is deprecated. Please do not add new features."
          echo "Only urgent bug fixes will be accepted."
          echo ""
          echo "See https://linear.app/chainguard/issue/SRE-179/move-terraform-infra-common-to-mono for more details."
          echo "If you need any help please reach out to the SRE team."
          echo "*******************************************************************"
          echo "# Deprecation Notice" >> "$GITHUB_STEP_SUMMARY"
          echo "This repository is deprecated. Please do not add new features." >> "$GITHUB_STEP_SUMMARY"
          echo "Only urgent bug fixes will be accepted." >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo "See https://linear.app/chainguard/issue/SRE-179/move-terraform-infra-common-to-mono for more details." >> "$GITHUB_STEP_SUMMARY"
          echo "If you need any help please reach out to the SRE team." >> "$GITHUB_STEP_SUMMARY"

      - uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        if: github.event_name == 'pull_request'
        with:
          github-token: ${{ steps.octo-sts.outputs.token }}
          script: |
            // 2. Prepare format of the comment
            const output = `### ⚠️ DEPRECATION NOTICE\nThis repository is deprecated. Please do not add new features. Only urgent bug fixes will be accepted.\n\nSee https://linear.app/chainguard/issue/SRE-179/move-terraform-infra-common-to-mono for more details.\nIf you need any help please reach out to the SRE team.\n`

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Block PR
        shell: bash
        run: |
          echo "::error::This repository is deprecated and new PRs are blocked."
          exit 1
