# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Image digest update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions: {}

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'chainguard-dev' }}

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: octo-sts/action@e480437973a6f6ac2e9caa40ecabedc870d76395 # v1.0.1
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: digestabot

      - uses: chainguard-dev/digestabot@a3b776c1ca57d3127c85578cde8fef6eed3c75d3 # v1.2.3
        id: digest-bot
        with:
          create-pr: false

      - name: Install terraform-docs
        uses: chainguard-dev/actions/setup-terraform-docs@cd899cc96227b82170571cad1c3d6378d8cba678 # v1.4.15

      - name: update docs
        run: ./hack/update-docs.sh

      - name: Check workspace
        id: create_pr_update
        shell: bash
        run: |
          git diff --stat
          echo "create_pr_update=false" >> $GITHUB_OUTPUT
          if [[ $(git diff --stat) != '' ]]; then
            echo "create_pr_update=true" >> $GITHUB_OUTPUT
          fi

      - uses: chainguard-dev/actions/setup-gitsign@cd899cc96227b82170571cad1c3d6378d8cba678 # v1.4.15
        if: ${{ steps.create_pr_update.outputs.create_pr_update == 'true' }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # v7.0.8
        if: ${{ steps.create_pr_update.outputs.create_pr_update == 'true' }}
        id: pull_request
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          commit-message: 'Update image digests and docs'
          title: 'Update image digests and docs'
          body: |
            This PR was automatically generated by the Chainguard Digest Bot.

            It updates the image digests in the Terraform configuration files.
          labels: 'automated pr'
          branch: 'update-digests'
          author: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
          committer: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
          sign-commits: 'true'
          delete-branch: true

      - name: Enable auto-merge
        if: ${{ steps.pull_request.outputs.pull-request-number != '' }}
        run: gh pr merge --auto --squash "https://github.com/chainguard-dev/terraform-infra-common/pull/${{ steps.pull_request.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
