# Copyright 2025 Chainguard, Inc.
# SPDX-License-Identifier: Apache-2.0

name: Image digest update

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

permissions: {}

jobs:
  image-update:
    name: Image digest update
    runs-on: ubuntu-latest
    if: ${{ github.repository_owner == 'chainguard-dev' }}

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: step-security/harden-runner@df199fb7be9f65074067a9eb93f12bb4c5547cf2 # v2.13.3
        with:
          egress-policy: audit

      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - uses: octo-sts/action@d6c70ad3b9ac85df6da6b9749014d7283987cfec # v1.0.3
        id: octo-sts
        with:
          scope: ${{ github.repository }}
          identity: digestabot

      - uses: chainguard-dev/digestabot@a3b776c1ca57d3127c85578cde8fef6eed3c75d3 # v1.2.3
        id: digest-bot
        with:
          create-pr: false

      - name: Install terraform-docs
        uses: chainguard-dev/actions/setup-terraform-docs@3e8a2a226fad9e1ecbf2d359b8a7697554a4ac6d # v1.5.10

      - name: update docs
        run: ./hack/update-docs.sh

      - name: Check workspace
        id: create_pr_update
        shell: bash
        run: |
          git diff --stat
          echo "create_pr_update=false" >> "$GITHUB_OUTPUT"
          if [[ "$(git diff --stat)" != '' ]]; then
            echo "create_pr_update=true" >> "$GITHUB_OUTPUT"
          fi

      - uses: chainguard-dev/actions/setup-gitsign@3e8a2a226fad9e1ecbf2d359b8a7697554a4ac6d # v1.5.10
        if: ${{ steps.create_pr_update.outputs.create_pr_update == 'true' }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@84ae59a2cdc2258d6fa0732dd66352dddae2a412 # v7.0.9
        if: ${{ steps.create_pr_update.outputs.create_pr_update == 'true' }}
        id: pull_request
        with:
          token: ${{ steps.octo-sts.outputs.token }}
          commit-message: 'Update image digests and docs'
          title: 'Update image digests and docs'
          body: |
            This PR was automatically generated by the Chainguard Digest Bot.

            It updates the image digests in the Terraform configuration files.
          labels: 'automated pr'
          branch: 'update-digests'
          author: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
          committer: "octo-sts[bot] <157150467+octo-sts[bot]@users.noreply.github.com>"
          sign-commits: 'true'
          delete-branch: true

      - name: Enable auto-merge
        if: ${{ steps.pull_request.outputs.pull-request-number != '' }}
        run: gh pr merge --auto --squash "https://github.com/chainguard-dev/terraform-infra-common/pull/${{ steps.pull_request.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
